version: '3.8'

services:
  mariadb:
    image: mariadb:11.8.2
    container_name: my-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: book_manager
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3307:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.2
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped