spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_manager
    username: myuser
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # 개발 중엔 update, 배포시 validate 또는 none 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  servlet:
    session:
      timeout: 10m

jwt:
  secret: VzS3N6v9y$B&E)H@McQfTjWnZr4u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPe
  access-expiration: 3600
  refresh-expiration: 604800

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE