spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_manager
    username: myuser
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # 개발 중엔 update, 배포시 validate 또는 none 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  servlet:
    session:
      timeout: 30m
