spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_manager
    username: myuser
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # 개발 중엔 update, 배포시 validate 또는 none 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

server:
  servlet:
    session:
      timeout: 10m

  tomcat:
    max-parameter-count: -1
    max-http-form-post-size: -1
    max-swallow-size: -1
    connection-timeout: 120000
    max-connections: 20000
    accept-count: 2000
    max-keep-alive-requests: -1
    keep-alive-timeout: 60000

jwt:
  secret: VzS3N6v9y$B&E)H@McQfTjWnZr4u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPe
  access-expiration: 3600
  refresh-expiration: 604800

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.apache.catalina: INFO
    org.apache.coyote: INFO
    org.apache.tomcat: INFO