spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/book_manager
    username: myuser
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # 개발 중엔 update, 배포시 validate 또는 none 추천
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB          # 업로드 가능한 파일 하나의 최대 크기
      max-request-size: 20MB       # 요청 전체의 최대 크기 (멀티 파일 업로드 시)
      enabled: true

server:
  servlet:
    session:
      timeout: 10m
  tomcat:
    max-http-form-post-size: -1    # POST 최대 크기 (-1이면 무제한)
    max-swallow-size: -1           # 파일 업로드 도중 클라이언트가 끊어도 버퍼링 크기 무제한
    max-part-count: 20

jwt:
  secret: VzS3N6v9y$B&E)H@McQfTjWnZr4u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPe
  access-expiration: 3600
  refresh-expiration: 604800

logging:
  level:
    org.apache.coyote: INFO
    org.apache.tomcat: INFO
    org.springframework.boot.web.embedded.tomcat: INFO